config/routes.rb
StecmsCoupon::Engine.routes.draw do
  resources :coupons
  resources :promos do
    resources :survey_forms, except: [ :index ]
  end

  resources :survey_forms, only: [] do
    resources :survey_questions, only: [ :create, :edit, :destroy ]
  end

  namespace :api do
    post 'promo/check', to: 'promos#check'
    post 'survey/submit_answer', to: 'survey#submit_answer'
    get 'promo/detail', to: 'promos#detail'

    resources :promos, only: [ :index ]

    resources :coupons, only: [:index, :show] do
      collection do
        post :use
      end
    end
  end
end

app/models/stecms_coupon.rb
module StecmsCoupon
  def self.table_name_prefix
    'stecms_coupon_'
  end
end

app/models/stecms_coupon/coupon.rb
class StecmsCoupon::Coupon < ActiveRecord::Base
  belongs_to :promo, class_name: 'StecmsCoupon::Promo', foreign_key: :stecms_coupon_promo_id
  before_validation :set_default_identifier, if: -> { self.identifier.blank? }

  validates :identifier, uniqueness: { case_sensitive: false }, presence: true
  validates :max_usage_times, numericality: { only_integer: true }

  def set_default_identifier
    self.identifier = generate_coupon_identifer
  end

  def generate_coupon_identifer
    loop do
      coupon_code = rand(36**12).to_s(36).upcase
      break coupon_code unless StecmsCoupon::Coupon.where(identifier: coupon_code).exists?
    end
  end

  def update_usage_coupon
    self.usage_times += 1
    self.save
  end

  def check_coupon_status
    return_data = { status: true, message: '', used: false, obj: nil }

    usage_after_count = self.usage_times + 1
    if self.max_usage_times < usage_after_count
      return_data[:message] = I18n.t("admin.coupon.status.successfully_used")
      return_data[:status]  = false
      return_data[:used]    = true
    else
      if self.valid_from.present? and self.valid_until.present?
        unless (self.valid_from.to_i .. self.valid_until.to_i).cover?(Time.now.to_i)
          return_data[:message] = I18n.t("admin.coupon.status.not_valid_coverage", start_at: I18n.l(self.valid_from, format: :long), ends_at: I18n.l(self.valid_until, format: :long))
          return_data[:status]  = false
        end
      elsif self.valid_from.present?
        if Time.now.to_i < self.valid_from.to_i
          return_data[:message] = I18n.t("admin.coupon.status.not_valid_yet", start_at: I18n.l(self.valid_from, format: :long) )
          return_data[:status]  = false
        end
      elsif self.valid_until.present?
        if Time.now.to_i > self.valid_until.to_i
          return_data[:message] = I18n.t("admin.coupon.status.expired", expired_at: I18n.l(self.valid_until, format: :long))
          return_data[:status]  = false
        end
      end
    end

    return_data
  end

  def self.check_valid_and_active(identifier, device)
    return_data = {status: true, message: '', obj: nil}
    coupon = StecmsCoupon::Coupon.where(identifier: identifier, device: device).last

    if coupon.present?
      return_data[:obj] = coupon

      data = coupon.check_coupon_status
      return_data[:status]  = data[:status]
      return_data[:message] = data[:message]
      return_data[:used]    = data[:used]
    else
      return_data[:message] = I18n.t("admin.coupon.status.not_found", identifier: identifier)
      return_data[:status]  = false
    end
    return_data
  end

  def self.generate_coupon(promo, device)
    StecmsCoupon::Coupon.create(stecms_coupon_promo_id: promo.id,
      device: device,
      valid_from: promo.coupon_usable_from,
      valid_until: promo.coupon_usable_until,
      generated_at: Time.zone.now,
      active: true,
      max_usage_times: promo.usage_coupon_times)
  end
end

app/models/stecms_coupon/promo.rb
class StecmsCoupon::Promo < ActiveRecord::Base
  mount_uploader :cover, FileUploader

  validates :name, presence: true
  validates :identifier,   presence: true, uniqueness: { case_sensitive: false }
  validates :valid_from, 	 presence: true, if: Proc.new { |a| a.valid_until.blank? }
  validates :valid_until , presence: true, if: Proc.new { |a| a.valid_from.blank? }
  validates :valid_until, date: { after: :valid_from }

  validates :coupon_usable_from,  date: { after_or_equal_to: :valid_from, allow_blank: true }
  validates :coupon_usable_until, date: { after: :coupon_usable_from,     allow_blank: true }

  validates :usage_time_per_device, numericality: { only_integer: true, greater_than_or_equal_to: 1 }
  validates :usage_coupon_times,    numericality: { only_integer: true, greater_than_or_equal_to: 1 }

  has_one  :survey,  :dependent => :destroy, class_name: 'StecmsCoupon::SurveyForm', foreign_key: :stecms_coupon_promo_id, inverse_of: :promo
  has_many :coupons, :dependent => :destroy, class_name: 'StecmsCoupon::Coupon',     foreign_key: :stecms_coupon_promo_id, inverse_of: :promo

  scope :visible,     -> { where(visible: true) }
  scope :not_expired, -> { where('valid_until >= ? AND valid_from <= ?', Time.zone.now, Time.zone.now) }
  scope :active,      -> { where(active: true) }

  def cover_image
    if cover.present?
      cover.full_url
    else
      "https://via.placeholder.com/320x240"
    end
  end

  def self.check_valid_and_active(identifier)
    return_data = {status: true, message: '', obj: nil}
    promo = StecmsCoupon::Promo.where(identifier: identifier).last

    if promo.present?
      return_data[:obj] = promo
      if promo.valid_from.present? and promo.valid_until.present?
        unless (promo.valid_from.to_i .. promo.valid_until.to_i).cover?(Time.now.to_i)
          return_data[:message] = I18n.t("admin.promo.status.not_valid_coverage", start_at: I18n.l(self.valid_from, format: :long), ends_at: I18n.l(self.valid_until, format: :long)) #'QR not valid time'
          return_data[:status]  = false
        end
      elsif promo.valid_from.present?
        if Time.now.to_i < promo.valid_from.to_i
          return_data[:message] = I18n.t("admin.promo.status.not_valid_yet", start_at: I18n.l(self.valid_from, format: :long)) #'Promo not started yet!'
          return_data[:status] = false
        end
      elsif promo.valid_until.present?
        if Time.now.to_i > promo.valid_until.to_i
          return_data[:message] = I18n.t("admin.promo.status.expired", expired_at: I18n.l(self.valid_until, format: :long))
          return_data[:status] = false
        end
      end
    else
      return_data[:message] = I18n.t("admin.promo.status.not_found", identifier: identifier)
      return_data[:status]  = false
    end
    return_data
  end

end

app/models/stecms_coupon/stecms_coupon.rb
module StecmsCoupon
  module StecmsCoupon
    def self.table_name_prefix
      'stecms_coupon_stecms_coupon_'
    end
  end
end

app/controllers/stecms_coupon/api/coupons_controller.rb
module StecmsCoupon
  module Api
    class CouponsController < ApiController
      include Rosebud

      params :index do
        requires :device
      end

      def index
        @coupons = ::StecmsCoupon::Coupon.includes(:promo).where(device: params[:device]).order(generated_at: :desc)
      end

      params :use do
        requires :identifier
        requires :device
      end

      def use
        @coupon = ::StecmsCoupon::Coupon.check_valid_and_active(params[:identifier], params[:device])

        ## if true,, update the usage time
        if @coupon[:status]
          @coupon[:obj].update_usage_coupon
        end
      end

      params :show do
        requires :id
      end

      def show
        @coupon = ::StecmsCoupon::Coupon.find(params[:id])
      end

    end
  end
end

app/controllers/stecms_coupon/api/promos_controller.rb
module StecmsCoupon
  module Api
    class PromosController < ApiController
      include Rosebud

      def index
        @promos = ::StecmsCoupon::Promo.active.visible.not_expired
      end

      params :detail do
        requires :identifier
      end

      def detail
        @promo = ::StecmsCoupon::Promo.active.where(identifier: params[:identifier]).last                       
      end

      params :check do
        requires :identifier
        requires :device
      end

      def check
        @coupon = nil
        @promo  = ::StecmsCoupon::Promo.check_valid_and_active(params[:identifier])

        check_coupon_num = ::StecmsCoupon::Coupon.where(stecms_coupon_promo_id: @promo[:obj].id, device: params[:device]).count
        if check_coupon_num > 0
          if check_coupon_num >= @promo[:obj].usage_time_per_device
            @promo[:status]  = false
            @promo[:message] = I18n.t("admin.promo.status.coupon_already_generated")
          end
        end

        ## generate coupon when no survey
        unless @promo[:obj].answer
          if @promo[:status]
            @coupon = ::StecmsCoupon::Coupon.generate_coupon(@promo[:obj], params[:device])
            @promo[:message] = I18n.t("admin.promo.status.coupon_added")
          end
        end
      end

    end
  end
end

app/controllers/stecms_coupon/api/survey_controller.rb
module StecmsCoupon
	module Api
	  class SurveyController < ApiController

	  	def submit_answer
	  		@coupon = nil
	  		@promo = ::StecmsCoupon::Promo.check_valid_and_active(params[:identifier])

	  		check_coupon_num = ::StecmsCoupon::Coupon.where(stecms_coupon_promo_id: @promo[:obj].id, device: params[:device]).count
  			if check_coupon_num > 0
  				if check_coupon_num >= @promo[:obj].usage_time_per_device
	  				@promo[:status] = false
  					@promo[:message] = 'Coupon for this promo already generated for this device'
  				end
  			end
	  		
	  		if @promo[:status]
	  			answer_ids = ::StecmsCoupon::SurveyAnswer.process_answer(params[:survey], @promo[:obj])
	  			@coupon = ::StecmsCoupon::Coupon.generate_coupon(@promo[:obj], params[:device])
	  			if @coupon 
	  				::StecmsCoupon::SurveyAnswer.set_coupon_on_answer(answer_ids, @coupon)
	  			end
	  		end

	  	end

  	end
  end
end

app/controllers/stecms_coupon/application_controller.rb
module StecmsCoupon
  class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception    
  end
end

app/controllers/stecms_coupon/coupons_controller.rb
require_dependency "stecms_coupon/application_controller"

module StecmsCoupon
  class CouponsController < BackendController
    before_action :set_coupon, only: [:show, :edit, :update, :destroy]
    before_action :set_active_page

    # GET /coupons
    def index
      authorize ::StecmsCoupon::Coupon
      @collection = ::StecmsCoupon::Coupon.all
    end

    # GET /coupons/1
    def show
    end

    # GET /coupons/new
    def new
      @coupon = ::StecmsCoupon::Coupon.new
      authorize @coupon
    end

    # GET /coupons/1/edit
    def edit
    end

    # POST /coupons
    def create
      @coupon = ::StecmsCoupon::Coupon.new(coupon_params)
      authorize @coupon

      if @coupon.save
        redirect_to edit_coupon_url(@coupon), notice: 'Coupon was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /coupons/1
    def update
      if @coupon.update(coupon_params)
        redirect_to edit_coupon_url(@coupon), notice: 'Coupon was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /coupons/1
    def destroy
      @coupon.destroy
      #redirect_to coupons_url, notice: 'Coupon was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_coupon
        @coupon = ::StecmsCoupon::Coupon.find(params[:id])
        authorize @coupon
      end

      # Only allow a trusted parameter "white list" through.
      def coupon_params
        params.require(:coupon).permit(:stecms_coupon_promo_id, :identifier, :device, :max_usage_times, :usage_times, :active, :valid_from, :valid_until, :generated_at)
      end

      def set_active_page
        @side_menu ||= "stecms_coupon"
      end
  end
end

app/controllers/stecms_coupon/promos_controller.rb
require_dependency "stecms_coupon/application_controller"

module StecmsCoupon
  class PromosController < BackendController
    before_action :set_promo, only: [:show, :edit, :update, :destroy]
    before_action :set_active_page

    # GET /promos
    def index
      authorize ::StecmsCoupon::Promo
      @collection = ::StecmsCoupon::Promo.all
    end

    # GET /promos/1
    def show
      respond_to do |format|
        format.html
        format.js
      end
    end

    # GET /promos/new
    def new
      @promo = ::StecmsCoupon::Promo.new
      authorize @promo
    end

    # GET /promos/1/edit
    def edit
    end

    # POST /promos
    def create
      @promo = ::StecmsCoupon::Promo.new(promo_params)
      authorize @promo

      if @promo.save
        redirect_to({action: :edit, id: @promo.id}, notice: 'Promo was successfully created.')
      else
        render :new
      end
    end

    # PATCH/PUT /promos/1
    def update
      if @promo.update(promo_params)
        redirect_to({action: :edit, id: @promo.id}, notice: 'Promo was successfully updated.')
      else
        render :edit
      end
    end

    # DELETE /promos/1
    def destroy
      @promo.destroy

      respond_to do |format|
        format.html do
          redirect_to promos_url, notice: 'Promo was successfully destroyed.'
        end
        format.js
      end
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_promo
        @promo = ::StecmsCoupon::Promo.find(params[:id])
        authorize @promo
      end

      # Only allow a trusted parameter "white list" through.
      def promo_params
        params.require(:promo).permit(
          :usage_coupon_times,
          :name,
          :identifier,
          :answer,
          :usage_time_per_device,
          :valid_from,
          :valid_until,
          :active,
          :cover,
          :description,
          :visible,
          :coupon_usable_from,
          :coupon_usable_until
        )
      end

      def set_active_page
        @side_menu ||= "stecms_promo"
      end
  end
end

app/controllers/stecms_coupon/survey_forms_controller.rb
require_dependency "stecms_coupon/application_controller"

module StecmsCoupon
  class SurveyFormsController < BackendController
    before_action :set_promo
    before_action :set_survey_form, only: [:show, :edit, :update, :destroy]
    before_action :set_active_page

    # GET /survey_forms
    # def index
    #   authorize ::StecmsCoupon::SurveyForm
    #   @collection = ::StecmsCoupon::SurveyForm.all
    # end

    # GET /survey_forms/1
    def show
    end

    # GET /survey_forms/new
    def new
      redirect_to edit_promo_survey_form_url(@promo, @promo.survey) and return if @promo.survey.present?
      @survey_form = ::StecmsCoupon::SurveyForm.new(stecms_coupon_promo_id: params[:promo_id])
      authorize @survey_form
    end

    # GET /survey_forms/1/edit
    def edit
    end

    # POST /survey_forms
    def create
      @survey_form = ::StecmsCoupon::SurveyForm.new(survey_form_params)
      authorize @survey_form

      if @survey_form.save
        redirect_to edit_promo_survey_form_url(@promo, @survey_form), notice: 'survey_form was successfully created.'
      else
        render :new
      end
    end

    # PATCH/PUT /survey_forms/1
    def update
      if @survey_form.update(survey_form_params)
        redirect_to edit_promo_survey_form_url(@promo, @survey_form), notice: 'survey_form was successfully updated.'
      else
        render :edit
      end
    end

    # DELETE /survey_forms/1
    def destroy
      @survey_form.destroy
      redirect_to survey_forms_url, notice: 'survey_form was successfully destroyed.'
    end

    private
      # Use callbacks to share common setup or constraints between actions.
      def set_survey_form
        @survey_form = ::StecmsCoupon::SurveyForm.find(params[:id])
        authorize @survey_form
      end

      def set_promo
        @promo = ::StecmsCoupon::Promo.find(params[:promo_id])
      end

      # Only allow a trusted parameter "white list" through.
      def survey_form_params
        params.require(:survey_form).permit(:name, :description, :stecms_coupon_promo_id,
          questions_attributes: [:id, :question, :input_type, :input_options, :input_placeholder, :input_label, :input_required, :_destroy])
      end

      def set_active_page
        @side_menu ||= "stecms_promo"
      end
  end
end

app/controllers/stecms_coupon/survey_questions_controller.rb
require_dependency "stecms_coupon/application_controller"

module StecmsCoupon
  class SurveyQuestionsController < BackendController
    before_action :set_survey_form

    def create
      @survey_question = @survey_form.questions.build
      authorize @survey_question
      @survey_question.save
    end

    def edit
      @survey_question = @survey_form.questions.find(params[:id])
      authorize @survey_question
    end

    def destroy
      @survey_question = @survey_form.questions.find(params[:id])
      authorize @survey_question
      @survey_question.destroy    
    end

    private
      def set_survey_form
        @survey_form = ::StecmsCoupon::SurveyForm.find(params[:survey_form_id])
      end
  end
end

app/helpers/stecms_coupon/application_helper.rb
module StecmsCoupon
  module ApplicationHelper
  end
end

app/helpers/stecms_coupon/coupons_helper.rb
module StecmsCoupon
  module CouponsHelper
    # returns splitted string with separator
    def formatted_coupon_identifier(identifier, length = 4, separator = "-")
      identifier.to_s.scan(/.{,#{length}}/).reject{|a| a.blank?}.join(separator)
    end
  end

end

app/helpers/stecms_coupon/promos_helper.rb
module StecmsCoupon
  module PromosHelper
  end
end

app/helpers/stecms_coupon/survey_form_helper.rb
module StecmsCoupon
  module SurveyFormHelper    
  end
end

app/views/stecms_coupon/promos/_form.html.haml
=form_for @promo do |f|
  - if @promo.errors.any?
    .alert.alert-danger{role: "alert"}
      %h4.alert-heading
        =t("errors.template.header", model: f.object.model_name.human, count: @promo.errors.count)
      %hr
      -@promo.errors.full_messages.each do |message|
        %div=message

  .form-row
    .col-sm-6
      .form-row
        .col-12
          %h6.text-primary
            =t("admin.promo.form.general")
      .form-row
        .form-group.col-12
          =f.label :name
          =f.text_field :name, class: 'form-control'
        .form-group.col-12
          =f.label :identifier
          =f.text_field :identifier, class: 'form-control', readonly: f.object.persisted?

        .form-group.col-12
          .form-check.backend-checkbox.check-left.mb-1.inline-check.mb-sm-0
            =f.check_box :active, class: 'form-check-input'
            =f.label :active, class: 'form-check-label'

          .form-check.backend-checkbox.check-left.mb-1.inline-check.mb-sm-0
            =f.check_box :visible, class: 'form-check-input'
            =f.label :visible, class: 'form-check-label'

          .form-check.backend-checkbox.check-left.mb-1.inline-check.mb-sm-0
            = f.check_box :answer, class: 'form-check-input'
            = f.label :answer, class: 'form-check-label'

      %hr.mt-2.mb-3

      .form-row
        .col-12
          %h6.text-primary
            =t("admin.promo.form.validity")

        .form-group.col-12.col-sm-6
          =f.label :valid_from
          =f.text_field :valid_from, class: 'flatpicker form-control'
        .form-group.col-12.col-sm-6
          =f.label :valid_until
          =f.text_field :valid_until, class: 'flatpicker form-control'

      %hr.mt-2.mb-3

      .form-row
        .col-12
          %h6.text-primary
            =t("admin.promo.form.coupon_usage")

        .form-group.col-12.col-sm-6
          =f.label :coupon_usable_from
          =f.text_field :coupon_usable_from, class: 'flatpicker form-control'
        .form-group.col-12.col-sm-6
          =f.label :coupon_usable_until
          =f.text_field :coupon_usable_until, class: 'flatpicker form-control'

      .form-row
        .form-group.col-12.col-sm-6
          =f.label :usage_time_per_device
          =f.text_field :usage_time_per_device, class: 'form-control'

        .form-group.col-12.col-sm-6
          =f.label :usage_coupon_times
          =f.text_field :usage_coupon_times, class: 'form-control'

    .col-sm-6
      .card.mb-0
        - if f.object.cover.present?
          =image_tag(f.object.cover.manipulate(size: '400x200').url, class: 'card-img-top')
        .card-body
          =f.label :cover
          =f.file_field :cover, class: 'form-control'


  %hr.mt-2.mb-3

  .form-row.mb-2.align-items-end
    .form-group.col-12
      =f.label :description
      =f.text_area :description, class: 'form-control', rows: 5


  .fixed-buttons
    =f.submit class: 'btn btn-primary'

    - if f.object.survey.present?
      =link_to t("admin.promo.form.edit_survey"), edit_promo_survey_form_path(f.object, f.object.survey), class: 'btn btn-danger'
    - else
      - if f.object.persisted?
        =link_to t("admin.promo.form.add_survey"), new_promo_survey_form_path(f.object), class: 'btn btn-danger'

app/views/stecms_coupon/promos/_show.haml
.stecms-coupon-promo-modal.text-left
  %button.remodal-close{data:{remodal_action: "close"}}

  .row.m-0.mt-3
    .col-12.p-0
      -# Divide information categories
      %ul.nav.nav-tabs
        %li.nav-item=link_to t("admin.promo.show.tabs.general"), "#promo-general", data: { toggle: "tab" }, class: "nav-link active"
        %li.nav-item=link_to t("admin.promo.show.tabs.survey"),  "#promo-survey", data: { toggle: "tab" }, class: "nav-link"

      .tab-content.mt-4
        .tab-pane.active#promo-general
          .row
            .col-12.col-sm-5.text-center.flex-fill.d-flex
              .card.mb-4
                .card-body.svg-responsive.p-2.align-items-center.d-flex.flex-fill.bg-light<>                  
                  %div
                    =RQRCode::QRCode.new(@promo.identifier).as_svg.html_safe

                .card-footer.bg-transparent
                  %h5.card-title.text-primary
                    .mb-2=t("admin.promo.show.identifier")
                    - if @promo.identifier.present?
                      %div=@promo.identifier
                    - else
                      .text-danter=t("admin.promo.show.alerts.identifier")

            .col-12.col-sm-7
              .card.mb-4
                .card-body
                  %h5.card-title.text-primary
                    =t("admin.promo.show.sections.general")

                  %dl.mb-0
                    %dt=t("admin.promo.show.name")
                    %dd=@promo.name

                    %dt=t("admin.promo.show.active")
                    %dd=t("#{@promo.active}")

                    %dt=t("admin.promo.show.answer")
                    %dd=t("#{@promo.answer}")

                    %dt=t("admin.promo.show.visible")
                    %dd=t("#{@promo.visible}")

                    %dt=t("admin.promo.show.usage_coupon_times")
                    %dd=@promo.usage_coupon_times

                    %dt
                      =t("admin.promo.show.usage_time_per_device")
                      %span.badge.badge-pill.badge-info.align-middle{:"data-toggle" => "tooltip", :"data-html" => "false", :"data-title" => t("admin.promo.show.help.usage_time_per_device")}
                        %i.fa.fa-info
                    %dd=@promo.usage_time_per_device

                    %dt=t("admin.promo.show.created_at")
                    %dd=l(@promo.created_at, format: :long)

                    %dt=t("admin.promo.show.updated_at")
                    %dd.mb-0=l(@promo.updated_at, format: :long)

          .row
            .col-12
              .card.mb-4
                .card-body
                  %h5.card-title.text-primary
                    =t("admin.promo.show.sections.validity")

                  %dl.mb-0
                    %dt=t("admin.promo.show.valid_from")
                    %dd=l(@promo.valid_from, format: :long)

                    %dt=t("admin.promo.show.valid_until")
                    %dd=l(@promo.valid_until, format: :long)

                    %dt=t("admin.promo.show.coupon_usable_from")
                    - if @promo.coupon_usable_from.present?
                      %dd=l(@promo.coupon_usable_from, format: :long)
                    - else
                      %dd=" - "

                    %dt=t("admin.promo.show.coupon_usable_until")
                    - if @promo.coupon_usable_until
                      %dd=l(@promo.coupon_usable_until, format: :long)
                    - else
                      " - "

        .tab-pane#promo-survey
          -if ( survey = @promo.survey ).present?
            - unless @promo.answer?
              .row
                .col-12
                  .alert.alert-warning
                    =raw(t("admin.promo.show.alerts.survey"))

            .row
              .col-12.col-sm-5
                .card.mb-4
                  .card-body
                    %h5.text-primary.card-title
                      =t("admin.promo.show.sections.survey.general")

                    %dl.mb-0
                      %dt=t("admin.promo.show.survey.name")
                      %dd=survey.name

                      %dt=t("admin.promo.show.survey.description")
                      %dd=survey.description.blank? ? " - " : survey.description

                      %dt=t("admin.promo.show.survey.created_at")
                      %dd=l(survey.created_at, format: :long)

                      %dt=t("admin.promo.show.survey.updated_at")
                      %dd.mb-0=l(survey.updated_at, format: :long)

              - questions = survey.questions
              .col-12.col-sm-7
                .card.mb-4.questions
                  .card-body
                    %h5.text-primary.card-title
                      =t("admin.promo.show.sections.survey.questions", size: questions.size)

                    - if questions.present?
                      - questions.each_with_index do |question, i|
                        %hr
                        %h5.mt-2.text-primary=i+1

                        %dl.mb-0
                          - [:question, :input_options, :input_placeholder, :input_label].each do |attr|
                            %dt=t("admin.promo.show.questions.#{attr}")
                            %dd=question.send(attr).present? ? question.send(attr) : "-"

                          %dt=t("admin.promo.show.questions.input_type")
                          %dd=t("admin.survey_form.field_types.#{question.input_type}")

                          %dt=t("admin.promo.show.questions.input_required")
                          %dd.mb-0=t("#{question.input_required}")

                    - else
                      .text-danger
                        =t("admin.promo.show.no_questions")

            .mb-3
              =link_to t("admin.promo.show.edit_survey"), edit_promo_survey_form_path(@promo, survey), class: 'btn btn-block btn-outline-danger'

          - else
            .text-danger.mb-3
              =t("admin.promo.show.no_survey")

            .mb-3
              =link_to t("admin.promo.show.add_survey"), new_promo_survey_form_path(@promo), class: 'btn btn-block btn-outline-danger'

        %div
          =link_to t("admin.words.edit"), edit_promo_path(@promo), class: 'btn btn-outline-primary btn-block'

app/views/stecms_coupon/promos/destroy.js.erb
$("#promo-<%= @promo.id %>").fadeOut(function() {
  $(this).remove();
})

app/views/stecms_coupon/promos/index.haml
=render layout: "stecms_coupon/shared/coupon_panel" do

  =render_card_box title: t("admin.promo.index.title"), collapse: false do
    - if @user.can(:create_promos)
      =link_to new_promo_path, class: 'btn btn-primary btn-sm' do
        %i.fa.fa-plus
        =t("admin.promo.index.new")

    .table-responsive
      %table.table.table-condensed.mt-3
        %thead
          %tr
            %th=t("admin.promo.table.identifier")
            %th=t("admin.promo.table.name")
            -#%th=t("admin.promo.table.answer")
            -#%th=t("admin.promo.table.usage_time_per_device")
            %th=t("admin.promo.table.active")
            %th=t("admin.promo.table.valid_from")
            %th=t("admin.promo.table.valid_until")
            %th

        %tbody
          - if @collection.present?
            - @collection.each do |item|
              %tr{id: "promo-#{item.id}"}
                %td=item.identifier
                %td=item.name
                %td=t("#{item.active}")
                %td=l(item.valid_from, format: :long) if item.valid_from.present?
                %td=l(item.valid_until, format: :long) if item.valid_from.present?
                %td
                  =link_to t("admin.words.edit"), edit_promo_path(item), class: 'mr-2'
                  =link_to t("admin.words.show"), promo_path(item), class: 'text-info mr-2', remote: true
                  -# TODO: override the confirm logic to open a prettier popup
                  -# refer to https://teamtreehouse.com/community/sweetalert-with-rails for inspiration
                  =link_to t("admin.words.delete"), promo_path(item), method: :delete, class: 'text-danger', remote: true, data: { confirm: t("admin.promo.index.delete", name: item.name) }